### PR TITLE
feat(proxy): allow to configure the proxy bind address

### PR DESCRIPTION
**Pull request by jperville**
This PR adds the `--bind-address` option to the proxy (defaulting to ":8082").

It is backward compatible and can be used to deploy kube-image-keeper in hostNetwork mode as described in #229 .

### CODE REVIEW

**Comment by jperville** [comment]
I take feedback since I'm not a go programmer (yet). I believe that my changes should work because they are consistent with the existing code.

**Comment by jperville** [comment]
Let me see if I can extend the helm chart a bit.

**Comment by jperville** [comment]
@paullaffitte  I added support for hostNetwork in the helm chart.

If the chart is installed with `proxy.hostNetwork: true`  then the proxy daemonset will listen to `proxy.hostIP:proxy.hostPort` (and the metrics to `proxy.hostIP:proxy.metricsPort` ).

Since exposing metrics over the hostNetwork is insecure, I force the metrics to listen to localhost instead of all interfaces when in hostNetwork mode. This has the effect of breaking the optional podmonitor feature but I can live with that, I would rather have a working kuik on hostNetwork without podmonitor than a working kuik with insecure metrics.

**Review by paullaffitte — APPROVED** [review]
LGTM!

**Pull request merged**
