### PR TITLE
docs: fixing registry.garbageCollectionSchedule parameter and some typos

### PR DESCRIPTION
**Pull request by felipewnp**

### CODE REVIEW

**Comment by paullaffitte** [comment]
Thanks for your contribution! Could you please reword your commit message in order to be compliant with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) please? Something like `docs: fixing registry.garbageCollectionSchedule parameter and some typos` would be great.

**Comment by felipewnp** [comment]
Done @paullaffitte !

**Comment by felipewnp** [comment]
@paullaffitte if anything else is needed, let me know.

**Pull request merged**
