### PR TITLE
feat: Add cachedimage pulling progress status

### PR DESCRIPTION
**Pull request by aDisplayName**
Add following property in CachedImage CRD
* `spec.progress.available`
* `spec.progress.total`

Upgrade Crd version from `kuikv1alpha1` to `kuikv1alpha1ext1`
Update the `status.progress.available` in CachedImage CRD every 5 seconds during the image pulling in cachedimage controller

### CODE REVIEW

**Comment by aDisplayName** [comment]
#401

**Comment by paullaffitte** [comment]
Thanks for your work! It looks interesting, this feature can be useful indeed. We will discuss soon with the rest of the team if we are interested in merging it. For my part I would do it. However there is a lot of commits and I will have to review all of them, which will take a bit of time so I hope you're not in a hurry 😅

**Comment by aDisplayName** [comment]
@paullaffitte , those commits can be grouped to the following three catalogs:
1. The CRD Change
2. The change of reference of `kuikv1alpha1` to `kuikv1alpha1ext1` in all relative area
3. The controller change in cachedimage_controller.go and registry.go.

If it makes your work easier, I can create a new PR with three consolidated commits.

Before I'm doing that, one decision I would seek from you, are
* should we change the CRD version `v1alpha1` for both cachedImage and repository, or just keep using it?
* If the decision is to change the CRD version, then which version would you like to be changed to?

Regards

**Comment by aDisplayName** [comment]
I'm closing this PR. As I've submitted a new PR #402  with all the clutters removed.

**Pull request closed without merging**
