### PR TITLE
 feat(cache): add AWS ECR auth support

### PR DESCRIPTION
**Pull request by gmykhailiuta**
Add support of AWS ECR.

Tested on both public and private ECR repositories:
```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  74s   default-scheduler  Successfully assigned dev-glr-linux-x86-cpu-s/test to ip-10-20-100-204.us-west-2.compute.internal
  Normal  Pulling    73s   kubelet            Pulling image "localhost:7439/<redacted>.dkr.ecr.us-west-2.amazonaws.com/<redacted>:alpine"
  Normal  Pulled     73s   kubelet            Successfully pulled image "localhost:7439/<redacted>.dkr.ecr.us-west-2.amazonaws.com/<redacted>:alpine" in 242.857334ms (242.896119ms including waiting)
  Normal  Created    73s   kubelet            Created container test
  Normal  Started    72s   kubelet            Started container test
```

### CODE REVIEW

**Review by blackliner — APPROVED** [review]

**Comment by aayushharwani-aidash** [comment]
I am getting this error, I am using version 1.3.0 

Failed to pull image "localhost:7439/1234567890123.dkr.ecr.us-east-1.amazonaws.com/flask": rpc error: code = Unknown desc = failed to pull and unpack image "localhost:7439/1234567890123.dkr.ecr.us-east-1.amazonaws.com/flask:latest": failed to resolve reference "localhost:7439/1234567890123.dkr.ecr.us-east-1.amazonaws.com/flask:latest": pulling from host localhost:7439 failed with status code [manifests latest]: 500 Internal Server Error

**Comment by gmykhailiuta** [comment]
@aayushharwani-aidash, try to create a separate issue and attach more information to it (logs, IAM role/policy used, etc.).

**Comment by felipewnp** [comment]
Hi @gmykhailiuta 

Do you mind explaining how this works? Or pointing to somewhere that does?

I'm lost on how to use this feature.

**Pull request merged**
