### PR TITLE
docs: image filtering

### LINKED ISSUE #440: Document the precedence of image selectors
Currently, there are a few options to configure which image should be cached:

- ignoredNamespaces
- ignoredImages
- acceptedImages
- objectSelector

Their combination is not clear, e.g. does the object selector apply on the top of accepted image or parallel? Having a clear order would help new users to configure kuik better.

### PR DESCRIPTION
**Pull request by plaffitt**
What do you think @zifeo? Is it clearer?

closes #440

### CODE REVIEW

**Comment by paullaffitte** [comment]
Almost, with the current `ignoredImages` setting you ignore all images.

**Comment by zifeo** [comment]
@paullaffitte Indeed, thanks. How would you configure to only cache docker.io ones? In my understanding this needs currently explicit denial of the other patterns or namespace.

**Comment by paullaffitte** [comment]
humm.. maybe I should add an example to the doc. I feel like it is not that easy to explain even though it is not very complicated. Something like:

---

Given a list of images and a image filtering configuration:

- `docker.io/library/nginx:stable-alpine`
- `docker.io/library/nginx:1.27`
- `nixery.dev/curl/kubectl`

```yaml
controllers:
  webhook:
    ignoredImages:
      - "^.+:[\\w-]*alpine[\\w-]*$"
    acceptedImages: 
      - "^docker\\.io/.*"
```

Performing the "ignore" step will remove the matching `docker.io/library/nginx:stable-alpine` image. And performing the accept step will remove the not matching `nixery.dev/curl/kubectl` image. Leaving us with only the `docker.io/library/nginx:1.27` image.

In the case of an empty `acceptedImages`, all images are accepted. In the case of an empty `ignoredImages`, none is ignored.

**Comment by zifeo** [comment]
@paullaffitte Your explanation are clear. Can you precise how objectSelector.matchExpressions enter the mix?

**Comment by plaffitt** [comment]
From the documentation:

> - Finally, kuik will only work on pods matching a specific selector. By default, the selector is empty, which means "match all the pods". The selector can be set with the Helm value `controllers.webhook.objectSelector.matchExpressions`.
>
> This logic isn't implemented by the kuik controllers or webhook directly, but through Kubernetes' standard webhook object selectors. In other words, these parameters end up in the `MutatingWebhookConfiguration` template to filter which pods get presented to kuik's webhook.

Why do you want to negate in the regex? You already can already do it by using either `ignoredImages` or `acceptedImages`.

**Comment by zifeo** [comment]
@plaffitt Sorted out what was bugging me, the accept image feature is only available since the last helm release and the lack of coherence messed with my global understanding. [This](https://github.com/enix/kube-image-keeper/pull/441#issuecomment-2507954909) should be enough to complete my doc request.

**Pull request merged**
